### ISSUE TITLE
新功能需求：按住Ctrl直接拖动

### ISSUE THREAD

**Issue by valuex** [SleepyBag/dragon-win#1]
能否增加以下功能：在标题栏上按住Ctrl键，并拖动，就可以直接将当前的office文件（word，ppt，excel）拖动到IM等软件窗口中。
据我所知，可以通过com获取当前office文件的路径，所以上述功能是可以在独立的软件中实现的，而不是要针对office开发插件。

**Comment by SleepyBag** [comment]
这似乎超出这个软件的功能范围，这确实更适合作为 office 插件
