### ISSUE TITLE
新功能请求：可以传递窗口弹出位置参数

### ISSUE THREAD

**Issue by valuex** [SleepyBag/dragon-win#2]
为了指定弹出窗口的位置，建议增加一个命令行开关。
-- cur 窗口弹出位置为当前光标位置
-p ax ay 窗口弹出位置为指定位置
请帮忙解决下，wpf实在是改不动啊，获取鼠标位置需要用到Windows form，但添加后就出现编译错误
'Forms' does not exist in the namespace system.windows

按如下链接说明，在csprj中添加了语句也不好使。 https://stackoverflow.com/questions/6639468/forms-does-not-exist-in-the-namespace-system-windows

```
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
</PropertyGroup>
```

**Comment by SleepyBag** [comment]
Windows Form 需要用 dotnet framework，现在的项目是 dotnet core 的。把框架改成 dotnet framework 应该就可以了，反正这个应该暂时没有跨平台需求

**Comment by SleepyBag** [comment]
@valuex 
更新了版本，可以指定窗口位置了。用法：
`--position mouse`
或者
`--position ax,ay`
